[package]
name = "vape"
description = "ｆｕｌｌ ｗｉｄｔｈ ａｅｓｔｈｅｔｉｃｓ"
version = "0.2.2"
authors = ["Joshua Li <josh@jrl.ninja>"]
license = "MIT"

homepage = "https://www.github.com/JoshuaRLi/vape"
repository = "https://www.github.com/JoshuaRLi/vape"
readme = "README.md"
keywords = ["aesthetic", "vaporwave", "fullwidth"]
categories = ["command-line-utilities", "text-processing"]

[badges]
travis-ci = { repository = "JoshuaRLi/vape" }

[dependencies]
getopts = "~0.2"
rand = { version = "~0.7", features = ["small_rng"] }

[[bin]]
name = "vape"
path = "src/main.rs"

# https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections
[profile.release]
panic = "abort"  # remove support for stack unwinding for smaller releases
lto = true
opt-level = "z"  # smallest build possible
codegen-units = 1  # disable parallel codegen because it prevents some optimizations
